function CoGTL = CoGThighL(in1,in2)
%COGTHIGHL
%    COGTL = COGTHIGHL(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 7.1.
%    28-Mar-2017 00:58:01

alphaL = in1(6,:);
l2 = in2(:,6);
lH = in2(:,3);
phi = in1(3,:);
x = in1(1,:);
y = in1(2,:);
t2 = alphaL+phi;
CoGTL = [x+lH.*sin(phi)+l2.*sin(t2);y-lH.*cos(phi)-l2.*cos(t2)];
