function dJFootL = dJcontPointL(in1,in2)
%DJCONTPOINTL
%    DJFOOTL = DJCONTPOINTL(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 7.1.
%    28-Mar-2017 00:58:00

alphaL = in1(6,:);
betaL = in1(7,:);
lH = in2(:,3);
lL2 = in2(:,7);
lL3 = in2(:,11);
phi = in1(3,:);
valphaL = in1(13,:);
vbetaL = in1(14,:);
vphi = in1(10,:);
t2 = alphaL+phi;
t3 = sin(t2);
t4 = lL2.*t3;
t5 = alphaL+betaL+phi;
t6 = sin(t5);
t7 = lL3.*t6;
t8 = t4+t7;
t9 = cos(t2);
t10 = lL2.*t9;
t11 = cos(t5);
t12 = lL3.*t11;
t13 = t10+t12;
t14 = t13.*valphaL;
t15 = lL3.*t11.*vbetaL;
t16 = valphaL+vbetaL+vphi;
dJFootL = reshape([0.0,0.0,0.0,0.0,-t8.*valphaL-vphi.*(t4+t7+lH.*sin(phi))-lL3.*t6.*vbetaL,t14+t15+vphi.*(t10+t12+lH.*cos(phi)),0.0,0.0,0.0,0.0,-t8.*valphaL-t8.*vphi-lL3.*t6.*vbetaL,t14+t15+t13.*vphi,-lL3.*t6.*t16,lL3.*t11.*t16],[2,7]);
