function dLengthL = dSpringLengthL(in1,in2)
%DSPRINGLENGTHL
%    DLENGTHL = DSPRINGLENGTHL(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 7.1.
%    28-Mar-2017 00:58:09

alphaL = in1(6,:);
betaL = in1(7,:);
lH = in2(:,3);
lL2 = in2(:,7);
lL3 = in2(:,11);
valphaL = in1(13,:);
vbetaL = in1(14,:);
t2 = alphaL+betaL;
t3 = sin(t2);
dLengthL = -(lH.*lL3.*t3.*valphaL+lH.*lL3.*t3.*vbetaL+lH.*lL2.*valphaL.*sin(alphaL)+lL2.*lL3.*vbetaL.*sin(betaL)).*1.0./sqrt(lH.^2+lL2.^2+lL3.^2+lH.*lL3.*cos(t2).*2.0+lH.*lL2.*cos(alphaL).*2.0+lL2.*lL3.*cos(betaL).*2.0);
