function dthetaL_BF = dThetaL_BF(in1,in2)
%DTHETAL_BF
%    DTHETAL_BF = DTHETAL_BF(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 7.1.
%    28-Mar-2017 00:58:11

alphaL = in1(6,:);
betaL = in1(7,:);
lH = in2(:,3);
lL2 = in2(:,7);
lL3 = in2(:,11);
phi = in1(3,:);
valphaL = in1(13,:);
vbetaL = in1(14,:);
vphi = in1(10,:);
t2 = alphaL+betaL+phi;
t3 = alphaL+phi;
t5 = cos(t2);
t6 = lL3.*t5;
t7 = sin(t2);
t8 = lL3.*t7;
t9 = cos(t3);
t10 = lL2.*t9;
t11 = sin(t3);
t12 = lL2.*t11;
t13 = cos(phi);
t14 = lH.*t13;
t15 = sin(phi);
t16 = lH.*t15;
t24 = imag(t6);
t25 = real(t8);
t26 = imag(t10);
t27 = real(t12);
t29 = real(t16);
t30 = imag(t14);
t4 = t24+t25+t26+t27+t29+t30;
t18 = real(t6);
t19 = imag(t8);
t20 = real(t10);
t21 = imag(t12);
t22 = real(t14);
t23 = imag(t16);
t17 = -t18+t19-t20+t21-t22+t23;
t28 = t18-t19+t20-t21+t22-t23;
t31 = t4.^2;
t32 = t28.^2;
t33 = 1.0./t28;
t34 = 1.0./t28.^2;
dthetaL_BF = vphi+(t32.*vbetaL.*(t33.*(t18-t19)+t4.*t34.*(t24+t25)))./(t31+t32)+(t32.*valphaL.*(t33.*(t18-t19+t20-t21)+t4.*t34.*(t24+t25+t26+t27)))./(t31+t17.^2);
