function dthetaL_HK = dThetaL_HK(in1,in2)
%DTHETAL_HK
%    DTHETAL_HK = DTHETAL_HK(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 7.1.
%    28-Mar-2017 00:58:11

alphaL = in1(6,:);
lL2 = in2(:,7);
phi = in1(3,:);
valphaL = in1(13,:);
vphi = in1(10,:);
t2 = alphaL+phi;
t4 = cos(t2);
t5 = lL2.*t4;
t6 = sin(t2);
t7 = lL2.*t6;
t3 = imag(t5)+real(t7);
t8 = imag(t7)-real(t5);
t10 = t6.*1i;
t11 = t4+t10;
t12 = lL2.*t11;
t9 = imag(t12);
t13 = real(t12);
dthetaL_HK = ((t3.^2+t8.^2).*(valphaL+vphi))./(t9.^2+t13.^2);
