function CoGB = posBody(in1,in2)
%POSBODY
%    COGB = POSBODY(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 7.1.
%    28-Mar-2017 00:58:00

x = in1(1,:);
y = in1(2,:);
CoGB = [x;y];
