function FootR = posFootR(in1,in2)
%POSFOOTR
%    FOOTR = POSFOOTR(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 7.1.
%    28-Mar-2017 00:58:01

alphaR = in1(4,:);
betaR = in1(5,:);
lH = in2(:,3);
lL2 = in2(:,7);
lL3 = in2(:,11);
phi = in1(3,:);
x = in1(1,:);
y = in1(2,:);
t2 = alphaR+phi;
t3 = alphaR+betaR+phi;
FootR = [x+lH.*sin(phi)+lL2.*sin(t2)+lL3.*sin(t3);y-lH.*cos(phi)-lL2.*cos(t2)-lL3.*cos(t3)];
