function LengthL = SpringLengthL(in1,in2)
%SPRINGLENGTHL
%    LENGTHL = SPRINGLENGTHL(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 7.1.
%    28-Mar-2017 00:58:09

alphaL = in1(6,:);
betaL = in1(7,:);
lH = in2(:,3);
lL2 = in2(:,7);
lL3 = in2(:,11);
LengthL = sqrt(lH.^2+lL2.^2+lL3.^2+lH.*lL3.*cos(alphaL+betaL).*2.0+lH.*lL2.*cos(alphaL).*2.0+lL2.*lL3.*cos(betaL).*2.0);
