function thetaR_HF = ThetaR_HF(in1,in2)
%THETAR_HF
%    THETAR_HF = THETAR_HF(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 8.0.
%    30-Nov-2018 23:09:57

alphaR = in1(4,:);
betaR = in1(5,:);
lL2 = in2(:,7);
lL3 = in2(:,11);
phi = in1(3,:);
t2 = alphaR+phi;
t3 = alphaR+betaR+phi;
thetaR_HF = angle(lL2.*cos(t2)+lL3.*cos(t3)-lL2.*sin(t2).*1i-lL3.*sin(t3).*1i);
