function dFootR = velFootR(in1,in2)
%VELFOOTR
%    DFOOTR = VELFOOTR(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 7.1.
%    28-Mar-2017 00:58:12

alphaR = in1(4,:);
betaR = in1(5,:);
lH = in2(:,3);
lL2 = in2(:,7);
lL3 = in2(:,11);
phi = in1(3,:);
valphaR = in1(11,:);
vbetaR = in1(12,:);
vphi = in1(10,:);
vx = in1(8,:);
vy = in1(9,:);
t2 = alphaR+phi;
t3 = cos(t2);
t4 = lL2.*t3;
t5 = alphaR+betaR+phi;
t6 = cos(t5);
t7 = lL3.*t6;
t8 = sin(t2);
t9 = lL2.*t8;
t10 = sin(t5);
t11 = lL3.*t10;
dFootR = [vx+valphaR.*(t4+t7)+vphi.*(t4+t7+lH.*cos(phi))+lL3.*t6.*vbetaR;vy+valphaR.*(t9+t11)+vphi.*(t9+t11+lH.*sin(phi))+lL3.*t10.*vbetaR];
