function CoGB = posBody(in1,in2)
%POSBODY
%    COGB = POSBODY(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 8.0.
%    30-Nov-2018 22:29:03

x = in1(1,:);
y = in1(2,:);
CoGB = [x;y];
