function CoGB = posBody(in1,in2)
%POSBODY
%    COGB = POSBODY(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 7.1.
%    02-Apr-2017 20:04:11

x = in1(1,:);
y = in1(2,:);
CoGB = [x;y];
