function dFootL = velFootL(in1,in2)
%VELFOOTL
%    DFOOTL = VELFOOTL(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 8.0.
%    30-Nov-2018 22:29:18

alphaL = in1(6,:);
betaL = in1(7,:);
lH = in2(:,3);
lL2 = in2(:,7);
lL3 = in2(:,11);
phi = in1(3,:);
valphaL = in1(13,:);
vbetaL = in1(14,:);
vphi = in1(10,:);
vx = in1(8,:);
vy = in1(9,:);
t2 = alphaL+phi;
t3 = cos(t2);
t4 = lL2.*t3;
t5 = alphaL+betaL+phi;
t6 = cos(t5);
t7 = lL3.*t6;
t8 = sin(t2);
t9 = lL2.*t8;
t10 = sin(t5);
t11 = lL3.*t10;
dFootL = [vx+valphaL.*(t4+t7)+vphi.*(t4+t7+lH.*cos(phi))+lL3.*t6.*vbetaL;vy+valphaL.*(t9+t11)+vphi.*(t9+t11+lH.*sin(phi))+lL3.*t10.*vbetaL];
