function CoGStanceThigh = CoGStanceThigh_MinCoord(in1,in2)
%COGSTANCETHIGH_MINCOORD
%    COGSTANCETHIGH = COGSTANCETHIGH_MINCOORD(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 8.0.
%    03-Dec-2018 11:57:17

l2 = in2(:,6);
lL2 = in2(:,7);
lL3 = in2(:,11);
qm1 = in1(1,:);
qm2 = in1(2,:);
t2 = qm1+qm2;
t3 = l2-lL2;
CoGStanceThigh = [-lL3.*sin(qm1)+t3.*sin(t2);lL3.*cos(qm1)-t3.*cos(t2)];
