function dqm = dq_MinCoord(in1,PI)
%DQ_MINCOORD
%    DQM = DQ_MINCOORD(IN1,PI)

%    This function was generated by the Symbolic Math Toolbox version 8.0.
%    02-Dec-2018 23:13:20

dalphaSwing = in1(4,:);
dalphaStance = in1(2,:);
dbetaSwing = in1(5,:);
dbetaStance = in1(1,:);
dphi = in1(3,:);
dqm = [dalphaStance+dbetaStance+dphi;-dbetaStance;-dalphaStance;dalphaSwing;dbetaSwing];
