function Hip = Hip_MinCoord(in1,in2)
%HIP_MINCOORD
%    HIP = HIP_MINCOORD(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 8.0.
%    03-Dec-2018 11:57:17

lL2 = in2(:,7);
lL3 = in2(:,11);
qm1 = in1(1,:);
qm2 = in1(2,:);
t2 = qm1+qm2;
Hip = [-lL3.*sin(qm1)-lL2.*sin(t2);lL3.*cos(qm1)+lL2.*cos(t2)];
