function qm1 = q1_MinCoord(in1,PI)
%Q1_MINCOORD
%    QM1 = Q1_MINCOORD(IN1,PI)

%    This function was generated by the Symbolic Math Toolbox version 8.0.
%    02-Dec-2018 18:10:24

alphaStance = in1(2,:);
betaStance = in1(1,:);
phi = in1(3,:);
qm1 = alphaStance+betaStance+phi;
