function qm2 = q2_MinCoord(in1,PI)
%Q2_MINCOORD
%    QM2 = Q2_MINCOORD(IN1,PI)

%    This function was generated by the Symbolic Math Toolbox version 8.0.
%    02-Dec-2018 18:10:24

betaStance = in1(1,:);
qm2 = -betaStance;
