function qm3 = q3_MinCoord(in1,PI)
%Q3_MINCOORD
%    QM3 = Q3_MINCOORD(IN1,PI)

%    This function was generated by the Symbolic Math Toolbox version 8.0.
%    02-Dec-2018 18:10:24

alphaStance = in1(2,:);
qm3 = PI.*2.0-alphaStance;
