function qm4 = q4_MinCoord(in1,PI)
%Q4_MINCOORD
%    QM4 = Q4_MINCOORD(IN1,PI)

%    This function was generated by the Symbolic Math Toolbox version 8.0.
%    02-Dec-2018 18:10:24

alphaSwing = in1(4,:);
qm4 = alphaSwing;
