function qm5 = q5_MinCoord(in1,PI)
%Q5_MINCOORD
%    QM5 = Q5_MINCOORD(IN1,PI)

%    This function was generated by the Symbolic Math Toolbox version 8.0.
%    02-Dec-2018 18:10:24

betaSwing = in1(5,:);
qm5 = betaSwing;
