function qm = q_MinCoord(in1,PI)
%Q_MINCOORD
%    QM = Q_MINCOORD(IN1,PI)

%    This function was generated by the Symbolic Math Toolbox version 8.0.
%    02-Dec-2018 23:13:20

alphaSwing = in1(4,:);
alphaStance = in1(2,:);
betaSwing = in1(5,:);
betaStance = in1(1,:);
phi = in1(3,:);
qm = [alphaStance+betaStance+phi;-betaStance;PI.*2.0-alphaStance;alphaSwing;betaSwing];
