function StanceKnee = StanceKnee_MinCoord(in1,in2)
%STANCEKNEE_MINCOORD
%    STANCEKNEE = STANCEKNEE_MINCOORD(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 8.0.
%    03-Dec-2018 11:57:17

lL3 = in2(:,11);
qm1 = in1(1,:);
StanceKnee = [-lL3.*sin(qm1);lL3.*cos(qm1)];
