function SwingKnee = SwingKnee_MinCoord(in1,in2)
%SWINGKNEE_MINCOORD
%    SWINGKNEE = SWINGKNEE_MINCOORD(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 8.0.
%    03-Dec-2018 11:57:18

PI = in2(:,13);
lL2 = in2(:,7);
lL3 = in2(:,11);
qm1 = in1(1,:);
qm2 = in1(2,:);
qm3 = in1(3,:);
qm4 = in1(4,:);
t2 = PI.*-2.0+qm1+qm2+qm3+qm4;
t3 = qm1+qm2;
SwingKnee = [-lL3.*sin(qm1)+lL2.*sin(t2)-lL2.*sin(t3);lL3.*cos(qm1)-lL2.*cos(t2)+lL2.*cos(t3)];
