function [perturbed_parameters] = sysParam_minCoord_pertrubed(scale,sysParam_minCoord)
    % scale all mass and inertia by "scale"
    
    % sysParam_minCoord = [param.m1 param.J1 param.lH ...
    %             param.m2 param.J2 param.l2 param.lL2 ...
    %             param.m3 param.J3 param.l3 param.lL3 param.g pi];
    
    perturbed_parameters = sysParam_minCoord.*...
        [scale scale 1, ...
        scale scale 1 1,...
        scale scale 1 1 1 1];
end

